### ISSUE TITLE
Update to v11

### ISSUE THREAD

**Issue by rlavkvmflzk** [Wibble199/FoundryVTT-Terrain-Height-Tools#1]
Hi. I was using this module very well. Thank you for creating the module, but  lancer system was recently updated to V11. Is there any chance you could update this module to work with V11? Thanks as always.

**Comment by Rugarpo99** [comment]
Hope he does it. This module is amazing. Thanks for making this man.

**Comment by Wibble199** [comment]
Thanks guys, the latest version (v0.2.0) should now work with Foundry v11. Let me know if you run into any issues.

**Comment by Rugarpo99** [comment]
Yeah it works, not issues for now. Thank you so much!

**Comment by rlavkvmflzk** [comment]
It works great. Thank you so much!
