### ISSUE TITLE
[Feature Request] Token Elevation Adjustment Based on Terrain Height

### ISSUE THREAD

**Issue by hylandpad** [Wibble199/FoundryVTT-Terrain-Height-Tools#11]
Feature Request: Adjust token elevation when a token moves into or out of a terrain cell that has height.

Token moves from 0 height > 3 height -> set token elevation to 3

Token moves from 3 height > 0 height -> set token elevation to 0

It might make sense to track a token's prior elevation in order to account for flying or hovering tokens

Flying token at elevation 8 >  3 height -> set elevation to 11

This might get complicated if the flyer moves from heightened terrain to heightened terrain, (IE - moves from 11 > 14 over a cover 6 object, would probably need to be smart enough to know to subtract the cover value of its previous terrain from its initial elevation) so initial elevation number might need to get tethered to elevation 0.

**Comment by Wibble199** [comment]
Thanks for the feature request, this should now be implemented from v0.3.6.
