### ISSUE TITLE
[FEATURE REQUEST] Detect Scene Grid Scale for Token Height

### ISSUE THREAD

**Issue by msprijatelj** [Wibble199/FoundryVTT-Terrain-Height-Tools#12]
# Description

Currently, Terrain Height Tools assumes a grid scale of 1 when calculating line of sight for tokens. This leads to a token height mismatch on grids with scales with values other than 1.

The case where I encountered this is when I set a scene's grid scale to 0.5, and doubled all my tokens' widths and heights to match. For a Size 1 token, instead of being treated as "Size 1", my tokens were treated as "Size 2" (or H2) when calculating line of sight. Ideally, it would be great if the token's "height" was calculated with grid scale in mind to save some mental math effort of "halving" all the displayed height values for a particular scene.

**Comment by Wibble199** [comment]
Thanks for the report, this should now be implemented from v0.3.6.
