### ISSUE TITLE
Removing tags from Grape Juice Isometrics post 0.4.0 update

### ISSUE THREAD

**Issue by mhildom** [Wibble199/FoundryVTT-Terrain-Height-Tools#15]
Noticed interesting interaction between Grape Juice Isometrics and Terrain-Height-Tools, when all were updated to their most up to date version.

Module and Foundry Versions:
Grape Juice Isometrics: 0.11.308.0
Grape Juice Isometrics Pro: 0.11.308.0
Terrain Height Tools: 0.4.4 (behavior begins starting with v 0.4.0, downgrading to 0.3.7 fixes interaction)
libWrapper: 1.13.2.0

Foundry V11 Build 315

Issue: After making any changes to a map with terrain-height-tools while the map was set to isometric with the isometrics mod, interacting with tokens or reloading the scene breaks the tokens visually and disables the isometric toggle.

Steps to recreate: 
1) Install all listed mods (pro is not needed, issue is with base version)
2) set scene to isometric mode
3) load tokens (for visual evidence)
4) make change with terrain height tools
5) reload scene or move tokens

I have raised this issue in the bugs section of the isometric mod discord, but after looking deeper into it, seems to be related more heavily to terrain-height-tools nuking the isometric mods tags

before making any changes to the terrain, I can run 
game.scenes.viewed?.getFlag("grape_juice-isometrics","is_isometric) 
and it will return true so long as you have the toggle on

after making changes to terrain and running the same command results in "undefined"

simply running 
game.scenes.viewed?.flags
before making changes shows both modules flags intact, but after making a change to the terrain, all tags related to isometrics have been removed. I would imagine this is the same for other mods that use tags, however I cannot confirm as I have not found another mod in my setup that relies on those flags.

Screenshots attached

![image](https://github.com/user-attachments/assets/f2ec5a32-afb7-4672-b1ce-bfdae1c36196)
![image](https://github.com/user-attachments/assets/ddce56ef-2953-4d70-a6cd-1ae9f4409acc)
![image](https://github.com/user-attachments/assets/99f508bb-a20b-4c87-8e8b-4955d2549f49)

**Comment by mhildom** [comment]
To add on, I manually set a test flag on lib-wrapper and recreated the steps to cause the issue, attached are screenshots of all tags.

Set the flag
![image](https://github.com/user-attachments/assets/08139651-3561-46f3-8259-cda553324470)

Before making terrain changes
![image](https://github.com/user-attachments/assets/5578ec4d-09c1-43ac-a613-ada66024149d)

After terrain changes
![image](https://github.com/user-attachments/assets/60cade45-7e55-4e40-8902-1995addeb789)

**Comment by Wibble199** [comment]
Thanks for testing that. If you're already on 0.4.x then that should be a safe change for you to make.

The problem that it was solving was that old data was being merged with new data when migrating from the v0.3.x data structure to the v0.4.x version. So I tried to make it clear out the existing data in that flag, but it must be clearing out all data from all flags.

I'm going to change it so that it stores whether or not a migration was done, and if so it'll explicitly `unsetFlag` first, before then using `setFlag`, which should be safer and not delete other flags.

**Comment by Wibble199** [comment]
@mhildom I've pushed v0.4.5 which should resolve the issue. If you can give it a go please, as there doesn't seem to be a public v11 version of Grape Juice Isometrics that I can test on.

**Comment by mhildom** [comment]
@Wibble199 Just updated to v0.4.6, issue seems to be resolved, able to use it properly and tags are being maintained. Thanks for the fast response!
