### ISSUE TITLE
Line of Sight

### ISSUE THREAD

**Issue by Rugarpo99** [Wibble199/FoundryVTT-Terrain-Height-Tools#2]
I have been testing the module in v11 and is the LoS calculations still a feature? Because it doesnt work and the player always have vision of everything

**Comment by Wibble199** [comment]
Hi, the line of sight feature is not yet completed. But, even then it will be a ruler-like tool which indicates where the line crosses or touches any grid cells and at what height. It will not actually affect the player's fog of war at all - if you wish to achieve this I would probably stick to using Foundry's walls.

**Comment by Rugarpo99** [comment]
Its ok tho thanks for everything anyway!
