### ISSUE TITLE
Font choices not saving

### ISSUE THREAD

**Issue by webhead9241** [Wibble199/FoundryVTT-Terrain-Height-Tools#3]
Hi, love the module! I'm just having one odd issue: Any time I open the configuration page, the fonts in all terrain types reset to Arial (even if I don't open the various submenus). This has the unfortunate side effect of causing all fonts on the board to be lost whenever I save changes. For reference, I am using Foundry v.11.315 and Terrain Height Tools v.0.20. Any insight or help you can provide would be much appreciated!

**Comment by Wibble199** [comment]
Thanks for the bug report :) Should be fixed in v0.2.1.
