### ISSUE TITLE
Publish on the foundry package listing

### ISSUE THREAD

**Issue by BoltsJ** [Wibble199/FoundryVTT-Terrain-Height-Tools#4]
The package listing doesn't have any releases, so this module can't be installed by searching in foundry. The package is registered, so you just need to add the releases to the page. 

Package management docs: https://foundryvtt.com/article/package-management

**Comment by Wibble199** [comment]
Thanks for the reminder. I had registered the package and forgotten about it! The latest versions of the module for Foundry v10.x and Foundry v11.x are on there now.
