### ISSUE TITLE
Setting to Respect Vision

### ISSUE THREAD

**Issue by Vixiea** [Wibble199/FoundryVTT-Terrain-Height-Tools#5]
Would it be possible to get a setting that respects vision so terrain layers that are within the fog of war aren't rendered for players?

**Comment by Wibble199** [comment]
Hi @Vixiea, sorry for not getting back to you sooner.

I'm not 100% sure what you mean, but at the moment the terrain map works in a very similar way to how tokens do in terms of being drawn to the scene. I.E. it will appear in the explored fog of war, but won't show in unexplored fog of war.

If you are requesting that it is hidden from unexplored fog of war, I unfortunately don't think this is possible with what Foundry exposes for module developers: it doesn't expose any kind of shape that can be used as a mask for the graphics, and trying to add my own in and keep it synchronised with the actual one would be a mammoth task.
