### ISSUE TITLE
Floating terrain or terrain at height > 0

### ISSUE THREAD

**Issue by Eliemer** [Wibble199/FoundryVTT-Terrain-Height-Tools#7]
Firstly, thank you so much for this module already. Works amazing for 99% of maps. For zero-g maps i would love to place cover floating in space which would involved setting two "height" values. the top and bottom of the terrain. Right now, all terrain starts at height 0.

I'm not requesting integration with Walls and Wall Height, just for a way to do floating terrain.

Pictured: A Terrain wall placed at H2-H4, which should not block line of sight for two S1 units at H0
![image](https://github.com/user-attachments/assets/07ba6280-9623-4396-a7c0-ce49a192dee8)
![image](https://github.com/user-attachments/assets/1e651705-03e8-4b80-b758-b507dcff23cc)

**Comment by Wibble199** [comment]
Thanks for the feature request. This has now been added in v0.3.3.
