### ISSUE TITLE
Automatically Select Token for LoS Tool

### ISSUE THREAD

**Issue by kaffo** [Wibble199/FoundryVTT-Terrain-Height-Tools#8]
The token LoS tool works incredibly well, however it would be nice if your currently selected token was automatically selected as the first token when you open the tool.
This functionally would be great for players and possibly nice for GMs in some cases.
My feeling is that the GM would unselect their current token or open the LoS tool and deselect their current token to make checks otherwise.
For players this is going to be much less frequent, as the majority of their checks are their own, selected token compared to another.

**Comment by Wibble199** [comment]
Thanks for the feature request. This has now been added in v0.3.3.
