### ISSUE TITLE
Add API to allow macros/modules to trigger line of sight check between tokens

### ISSUE THREAD

**Issue by BadIdeasBureau** [Wibble199/FoundryVTT-Terrain-Height-Tools#9]
Currently, the API provides functions to allow triggering a LoS check between points.

It would also be useful to be able to trigger this between tokens, as per the new LoS tool - either by an API function which takes two tokens as parameters (e.g. by id) and shows the LoS ruler between them, or by API functions which take a single token as a parameter and display the LoS ruler once both are set.

My use case is an in-person game using Material Plane - an infra-red tracking setup for physical minis which comes with a "pen" that can be used to trigger macros.  While it's possible to treat this as a mouse (and use the LoS tool via the current UX), it's clunky, so it would be much smoother for me to be able to select the tokens using the pen and trigger a macro to show the LoS calculation.

This could also be used to, e.g. provide a macro to allow the user to draw the LoS ruler between their controlled token and a targeted token.

**Comment by Wibble199** [comment]
Thanks for the feature request. This has now been added in v0.3.3.
